"""Build file for private bzlmod extensions."""

package(default_visibility = ["//visibility:private"])

# Private extensions for internal use only
# Currently unused - all extensions are public

exports_files(glob(["*.bzl"]))